// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Shipping.Infra.Db.Contexts.ShippingDbContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Shipping.Infra.Db.Contexts.ShippingDbContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705110042_Anonymous_Account")]
    partial class Anonymous_Account
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shipping")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.AuditLog.Domain.AuditHistoryLogAggregate.AuditHistoryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ModificationDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modification_date_utc");

                    b.Property<string>("ModificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modification_type");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_user_id");

                    b.Property<string>("ObjectFullType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_full_type");

                    b.Property<string>("ObjectIds")
                        .HasColumnType("text")
                        .HasColumnName("object_ids");

                    b.Property<string>("ObjectNewValues")
                        .HasColumnType("text")
                        .HasColumnName("object_new_values");

                    b.Property<string>("ObjectOriginalValues")
                        .HasColumnType("text")
                        .HasColumnName("object_original_values");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ownership_type");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_history_log");

                    b.ToTable("audit_history_log", "audit_log", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Shipping.Domain.AccountShippingAddressAggregate.AccountShippingAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressLine")
                        .HasColumnType("text")
                        .HasColumnName("address_line");

                    b.Property<int?>("ApartmentNo")
                        .HasColumnType("integer")
                        .HasColumnName("apartment_no");

                    b.Property<string>("BuildingNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("building_no");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("district_id");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<Guid>("NeighborhoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("neighborhood_id");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_account_id");

                    b.Property<string>("Postcode")
                        .HasColumnType("text")
                        .HasColumnName("postcode");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.HasKey("Id")
                        .HasName("pk_account_shipping_address");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_account_shipping_address_city_id");

                    b.HasIndex("DistrictId")
                        .HasDatabaseName("ix_account_shipping_address_district_id");

                    b.HasIndex("NeighborhoodId")
                        .HasDatabaseName("ix_account_shipping_address_neighborhood_id");

                    b.HasIndex("OwnerAccountId")
                        .HasDatabaseName("ix_account_shipping_address_owner_account_id");

                    b.ToTable("account_shipping_address", "shipping");
                });

            modelBuilder.Entity("Modules.Shipping.Domain.CityAggregate.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_city");

                    b.ToTable("city", "shipping");
                });

            modelBuilder.Entity("Modules.Shipping.Domain.DistrictAggregate.District", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_district");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_district_city_id");

                    b.ToTable("district", "shipping");
                });

            modelBuilder.Entity("Modules.Shipping.Domain.NeighborhoodAggregate.Neighborhood", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("district_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_neighborhood");

                    b.HasIndex("DistrictId")
                        .HasDatabaseName("ix_neighborhood_district_id");

                    b.ToTable("neighborhood", "shipping");
                });

            modelBuilder.Entity("Modules.Shipping.Domain.ShippingFeeAggregate.ShippingFee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("district_id");

                    b.Property<Guid>("NeighborhoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("neighborhood_id");

                    b.HasKey("Id")
                        .HasName("pk_shipping_fee");

                    b.ToTable("shipping_fee", "shipping");
                });

            modelBuilder.Entity("Modules.Shipping.Domain.AccountShippingAddressAggregate.AccountShippingAddress", b =>
                {
                    b.HasOne("Modules.Shipping.Domain.CityAggregate.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_shipping_address_city_city_id");

                    b.HasOne("Modules.Shipping.Domain.DistrictAggregate.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_shipping_address_district_district_id");

                    b.HasOne("Modules.Shipping.Domain.NeighborhoodAggregate.Neighborhood", "Neighborhood")
                        .WithMany()
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_account_shipping_address_neighborhood_neighborhood_id");

                    b.Navigation("City");

                    b.Navigation("District");

                    b.Navigation("Neighborhood");
                });

            modelBuilder.Entity("Modules.Shipping.Domain.DistrictAggregate.District", b =>
                {
                    b.HasOne("Modules.Shipping.Domain.CityAggregate.City", null)
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_district_city_city_id");
                });

            modelBuilder.Entity("Modules.Shipping.Domain.NeighborhoodAggregate.Neighborhood", b =>
                {
                    b.HasOne("Modules.Shipping.Domain.DistrictAggregate.District", null)
                        .WithMany("Neighborhoods")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_neighborhood_district_district_id");
                });

            modelBuilder.Entity("Modules.Shipping.Domain.ShippingFeeAggregate.ShippingFee", b =>
                {
                    b.OwnsOne("Haskap.EShopping.Domain.Common.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ShippingFeeId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("price_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("price_value");

                            b1.HasKey("ShippingFeeId");

                            b1.ToTable("shipping_fee", "shipping");

                            b1.WithOwner()
                                .HasForeignKey("ShippingFeeId")
                                .HasConstraintName("fk_shipping_fee_shipping_fee_id");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Shipping.Domain.CityAggregate.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Modules.Shipping.Domain.DistrictAggregate.District", b =>
                {
                    b.Navigation("Neighborhoods");
                });
#pragma warning restore 612, 618
        }
    }
}
