// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Account.Infra.Db.Contexts.AccountDbContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Account.Infra.Db.Contexts.AccountDbContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705105618_Phone_Number_Added")]
    partial class Phone_Number_Added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("account")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Account.Domain.AccountAggregate.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("text")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.ToTable("account", "account");
                });

            modelBuilder.Entity("Modules.Account.Domain.AccountAggregate.AccountRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_account_role");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_account_role_account_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_account_role_role_id");

                    b.ToTable("account_role", "account");
                });

            modelBuilder.Entity("Modules.Account.Domain.AccountAggregate.OpenLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("browser");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("RemoteIpAddress")
                        .HasColumnType("text")
                        .HasColumnName("remote_ip_address");

                    b.Property<DateTime>("UtcLastSeenDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("utc_last_seen_date_time");

                    b.Property<DateTime>("UtcLoginDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("utc_login_date_time");

                    b.HasKey("Id")
                        .HasName("pk_open_login");

                    b.HasIndex("AccountId", "Id")
                        .HasDatabaseName("ix_open_login_account_id_id");

                    b.ToTable("open_login", "account");
                });

            modelBuilder.Entity("Modules.Account.Domain.RoleAggregate.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.ToTable("role", "account");
                });

            modelBuilder.Entity("Modules.AuditLog.Domain.AuditHistoryLogAggregate.AuditHistoryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ModificationDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modification_date_utc");

                    b.Property<string>("ModificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modification_type");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_user_id");

                    b.Property<string>("ObjectFullType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_full_type");

                    b.Property<string>("ObjectIds")
                        .HasColumnType("text")
                        .HasColumnName("object_ids");

                    b.Property<string>("ObjectNewValues")
                        .HasColumnType("text")
                        .HasColumnName("object_new_values");

                    b.Property<string>("ObjectOriginalValues")
                        .HasColumnType("text")
                        .HasColumnName("object_original_values");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ownership_type");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_history_log");

                    b.ToTable("audit_history_log", "audit_log", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Account.Domain.AccountAggregate.Account", b =>
                {
                    b.OwnsMany("Haskap.DddBase.Domain.Common.Permission", "Permissions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("account_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("pk_account_permissions");

                            b1.HasIndex("AccountId")
                                .HasDatabaseName("ix_account_permissions_account_id");

                            b1.ToTable("account_permissions", "account");

                            b1.WithOwner()
                                .HasForeignKey("AccountId")
                                .HasConstraintName("fk_account_permissions_account_account_id");
                        });

                    b.OwnsOne("Modules.Account.Domain.AccountAggregate.Credentials", "Credentials", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("credentials_username");

                            b1.HasKey("AccountId");

                            b1.HasIndex("Username")
                                .HasDatabaseName("ix_account_credentials_username");

                            b1.ToTable("account", "account");

                            b1.WithOwner()
                                .HasForeignKey("AccountId")
                                .HasConstraintName("fk_account_account_id");

                            b1.OwnsOne("Modules.Account.Domain.AccountAggregate.Password", "Password", b2 =>
                                {
                                    b2.Property<Guid>("CredentialsAccountId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("HashedValue")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("credentials_password_hashed_value");

                                    b2.HasKey("CredentialsAccountId");

                                    b2.ToTable("account", "account");

                                    b2.WithOwner()
                                        .HasForeignKey("CredentialsAccountId")
                                        .HasConstraintName("fk_account_account_id");

                                    b2.OwnsOne("Modules.Account.Domain.AccountAggregate.Salt", "Salt", b3 =>
                                        {
                                            b3.Property<Guid>("PasswordCredentialsAccountId")
                                                .HasColumnType("uuid")
                                                .HasColumnName("id");

                                            b3.Property<string>("Value")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("credentials_password_salt_value");

                                            b3.HasKey("PasswordCredentialsAccountId");

                                            b3.ToTable("account", "account");

                                            b3.WithOwner()
                                                .HasForeignKey("PasswordCredentialsAccountId")
                                                .HasConstraintName("fk_account_account_id");
                                        });

                                    b2.Navigation("Salt")
                                        .IsRequired();
                                });

                            b1.Navigation("Password")
                                .IsRequired();
                        });

                    b.OwnsOne("Modules.Account.Domain.AccountAggregate.LoginAttempt", "LoginAttempt", b1 =>
                        {
                            b1.Property<Guid>("AccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("FailedAttemptCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("login_attempt_failed_attempt_count");

                            b1.Property<DateTime?>("LastFailedAttemptUtcDateTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("login_attempt_last_failed_attempt_utc_date_time");

                            b1.HasKey("AccountId");

                            b1.ToTable("account", "account");

                            b1.WithOwner()
                                .HasForeignKey("AccountId")
                                .HasConstraintName("fk_account_account_id");
                        });

                    b.Navigation("Credentials")
                        .IsRequired();

                    b.Navigation("LoginAttempt")
                        .IsRequired();

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Modules.Account.Domain.AccountAggregate.AccountRole", b =>
                {
                    b.HasOne("Modules.Account.Domain.AccountAggregate.Account", null)
                        .WithMany("Roles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_role_account_account_id");

                    b.HasOne("Modules.Account.Domain.RoleAggregate.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_role_role_role_id");
                });

            modelBuilder.Entity("Modules.Account.Domain.AccountAggregate.OpenLogin", b =>
                {
                    b.HasOne("Modules.Account.Domain.AccountAggregate.Account", null)
                        .WithMany("OpenLogins")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_open_login_account_account_id");
                });

            modelBuilder.Entity("Modules.Account.Domain.RoleAggregate.Role", b =>
                {
                    b.OwnsMany("Haskap.DddBase.Domain.Common.Permission", "Permissions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("name");

                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uuid")
                                .HasColumnName("role_id");

                            b1.HasKey("Id")
                                .HasName("pk_role_permissions");

                            b1.HasIndex("RoleId")
                                .HasDatabaseName("ix_role_permissions_role_id");

                            b1.ToTable("role_permissions", "account");

                            b1.WithOwner()
                                .HasForeignKey("RoleId")
                                .HasConstraintName("fk_role_permissions_role_role_id");
                        });

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Modules.Account.Domain.AccountAggregate.Account", b =>
                {
                    b.Navigation("OpenLogins");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
