// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Basket.Infra.Db.Contexts.BasketDbContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Basket.Infra.Db.Contexts.BasketDbContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624195647_Rename")]
    partial class Rename
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("basket")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.AuditLog.Domain.AuditHistoryLogAggregate.AuditHistoryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ModificationDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modification_date_utc");

                    b.Property<string>("ModificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modification_type");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_user_id");

                    b.Property<string>("ObjectFullType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_full_type");

                    b.Property<string>("ObjectIds")
                        .HasColumnType("text")
                        .HasColumnName("object_ids");

                    b.Property<string>("ObjectNewValues")
                        .HasColumnType("text")
                        .HasColumnName("object_new_values");

                    b.Property<string>("ObjectOriginalValues")
                        .HasColumnType("text")
                        .HasColumnName("object_original_values");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ownership_type");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_history_log");

                    b.ToTable("audit_history_log", "audit_log", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Basket.Domain.BasketAggregate.Basket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<Guid?>("CreatedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_user_id");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_user_id");

                    b.Property<Guid?>("OwnerAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_account_id");

                    b.HasKey("Id")
                        .HasName("pk_basket");

                    b.ToTable("basket", "basket");
                });

            modelBuilder.Entity("Modules.Basket.Domain.BasketAggregate.BasketAppliedSpecialCoupon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("uuid")
                        .HasColumnName("basket_id");

                    b.Property<Guid>("SpecialCouponId")
                        .HasColumnType("uuid")
                        .HasColumnName("special_coupon_id");

                    b.HasKey("Id")
                        .HasName("pk_basket_applied_special_coupon");

                    b.HasIndex("BasketId")
                        .HasDatabaseName("ix_basket_applied_special_coupon_basket_id");

                    b.ToTable("basket_applied_special_coupon", "basket");
                });

            modelBuilder.Entity("Modules.Basket.Domain.BasketAggregate.BasketItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("uuid")
                        .HasColumnName("basket_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_basket_item");

                    b.HasIndex("BasketId")
                        .HasDatabaseName("ix_basket_item_basket_id");

                    b.ToTable("basket_item", "basket");
                });

            modelBuilder.Entity("Modules.Basket.Domain.BasketAggregate.BasketRemovedRegularCoupon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("uuid")
                        .HasColumnName("basket_id");

                    b.Property<Guid>("RegularCouponId")
                        .HasColumnType("uuid")
                        .HasColumnName("regular_coupon_id");

                    b.HasKey("Id")
                        .HasName("pk_basket_removed_regular_coupon");

                    b.HasIndex("BasketId")
                        .HasDatabaseName("ix_basket_removed_regular_coupon_basket_id");

                    b.ToTable("basket_removed_regular_coupon", "basket");
                });

            modelBuilder.Entity("Modules.Basket.Domain.BasketAggregate.BasketAppliedSpecialCoupon", b =>
                {
                    b.HasOne("Modules.Basket.Domain.BasketAggregate.Basket", null)
                        .WithMany("AppliedSpecialCoupons")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_basket_applied_special_coupon_basket_basket_id");
                });

            modelBuilder.Entity("Modules.Basket.Domain.BasketAggregate.BasketItem", b =>
                {
                    b.HasOne("Modules.Basket.Domain.BasketAggregate.Basket", null)
                        .WithMany("Items")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_basket_item_basket_basket_id");
                });

            modelBuilder.Entity("Modules.Basket.Domain.BasketAggregate.BasketRemovedRegularCoupon", b =>
                {
                    b.HasOne("Modules.Basket.Domain.BasketAggregate.Basket", null)
                        .WithMany("RemovedRegularCoupons")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_basket_removed_regular_coupon_basket_basket_id");
                });

            modelBuilder.Entity("Modules.Basket.Domain.BasketAggregate.Basket", b =>
                {
                    b.Navigation("AppliedSpecialCoupons");

                    b.Navigation("Items");

                    b.Navigation("RemovedRegularCoupons");
                });
#pragma warning restore 612, 618
        }
    }
}
