<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Modules.Account.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Modules.Account.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

</Project>
