// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Order.Infra.Db.Contexts.OrderDbContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Order.Infra.Db.Contexts.OrderDbContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707134510_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("order")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.AuditLog.Domain.AuditHistoryLogAggregate.AuditHistoryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ModificationDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modification_date_utc");

                    b.Property<string>("ModificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modification_type");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_user_id");

                    b.Property<string>("ObjectFullType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_full_type");

                    b.Property<string>("ObjectIds")
                        .HasColumnType("text")
                        .HasColumnName("object_ids");

                    b.Property<string>("ObjectNewValues")
                        .HasColumnType("text")
                        .HasColumnName("object_new_values");

                    b.Property<string>("ObjectOriginalValues")
                        .HasColumnType("text")
                        .HasColumnName("object_original_values");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ownership_type");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_history_log");

                    b.ToTable("audit_history_log", "audit_log", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Order.Domain.OrderAggregate.AppliedCoupon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsSpecialCoupon")
                        .HasColumnType("boolean")
                        .HasColumnName("is_special_coupon");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("OwnerCouponId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_coupon_id");

                    b.HasKey("Id")
                        .HasName("pk_applied_coupon");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_applied_coupon_order_id");

                    b.ToTable("applied_coupon", "order");
                });

            modelBuilder.Entity("Modules.Order.Domain.OrderAggregate.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("SlugValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug_value");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<string>("VariantSkuValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("variant_sku_value");

                    b.HasKey("Id")
                        .HasName("pk_item");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_item_order_id");

                    b.ToTable("item", "order");
                });

            modelBuilder.Entity("Modules.Order.Domain.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("HasFreeShippingCoupon")
                        .HasColumnType("boolean")
                        .HasColumnName("has_free_shipping_coupon");

                    b.HasKey("Id")
                        .HasName("pk_order");

                    b.ToTable("order", "order");
                });

            modelBuilder.Entity("Modules.Order.Domain.OrderAggregate.AppliedCoupon", b =>
                {
                    b.HasOne("Modules.Order.Domain.OrderAggregate.Order", null)
                        .WithMany("AppliedCoupons")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applied_coupon_order_order_id");

                    b.OwnsOne("Haskap.EShopping.Domain.Common.Money", "DiscountAmount", b1 =>
                        {
                            b1.Property<Guid>("AppliedCouponId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("discount_amount_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("discount_amount_value");

                            b1.HasKey("AppliedCouponId");

                            b1.ToTable("applied_coupon", "order");

                            b1.WithOwner()
                                .HasForeignKey("AppliedCouponId")
                                .HasConstraintName("fk_applied_coupon_applied_coupon_id");
                        });

                    b.Navigation("DiscountAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Order.Domain.OrderAggregate.Item", b =>
                {
                    b.HasOne("Modules.Order.Domain.OrderAggregate.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_order_order_id");

                    b.OwnsOne("Haskap.EShopping.Domain.Common.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("price_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("price_value");

                            b1.HasKey("ItemId");

                            b1.ToTable("item", "order");

                            b1.WithOwner()
                                .HasForeignKey("ItemId")
                                .HasConstraintName("fk_item_item_id");
                        });

                    b.OwnsOne("Haskap.EShopping.Domain.Common.Money", "Total", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("total_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("total_value");

                            b1.HasKey("ItemId");

                            b1.ToTable("item", "order");

                            b1.WithOwner()
                                .HasForeignKey("ItemId")
                                .HasConstraintName("fk_item_item_id");
                        });

                    b.OwnsOne("Haskap.EShopping.Domain.Common.Money", "TotalWithDiscount", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("total_with_discount_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("total_with_discount_value");

                            b1.HasKey("ItemId");

                            b1.ToTable("item", "order");

                            b1.WithOwner()
                                .HasForeignKey("ItemId")
                                .HasConstraintName("fk_item_item_id");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Total")
                        .IsRequired();

                    b.Navigation("TotalWithDiscount")
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Order.Domain.OrderAggregate.Order", b =>
                {
                    b.OwnsOne("Modules.Order.Domain.OrderAggregate.Account", "Account", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("account_email_address");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("account_first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("account_last_name");

                            b1.Property<Guid?>("OwnerAccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("account_owner_account_id");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("account_phone_number");

                            b1.HasKey("OrderId");

                            b1.ToTable("order", "order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_order_order_id");
                        });

                    b.OwnsOne("Modules.Order.Domain.OrderAggregate.Code", "Code", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("code_value");

                            b1.HasKey("OrderId");

                            b1.ToTable("order", "order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_order_order_id");
                        });

                    b.OwnsOne("Haskap.EShopping.Domain.Common.Money", "ShippingFee", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_fee_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("shipping_fee_value");

                            b1.HasKey("OrderId");

                            b1.ToTable("order", "order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_order_order_id");
                        });

                    b.OwnsOne("Haskap.EShopping.Domain.Common.Money", "Total", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("total_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("total_value");

                            b1.HasKey("OrderId");

                            b1.ToTable("order", "order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_order_order_id");
                        });

                    b.OwnsOne("Haskap.EShopping.Domain.Common.Money", "TotalWithDiscount", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("total_with_discount_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("total_with_discount_value");

                            b1.HasKey("OrderId");

                            b1.ToTable("order", "order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_order_order_id");
                        });

                    b.OwnsOne("Modules.Order.Domain.OrderAggregate.ShippingAddress", "ShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AddressLine")
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_address_line");

                            b1.Property<int?>("ApartmentNo")
                                .HasColumnType("integer")
                                .HasColumnName("shipping_address_apartment_no");

                            b1.Property<string>("BuildingNo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_building_no");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_city_name");

                            b1.Property<string>("DistrictName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_district_name");

                            b1.Property<int?>("Floor")
                                .HasColumnType("integer")
                                .HasColumnName("shipping_address_floor");

                            b1.Property<string>("NeighborhoodName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_neighborhood_name");

                            b1.Property<Guid>("OwnerShippingAddressId")
                                .HasColumnType("uuid")
                                .HasColumnName("shipping_address_owner_shipping_address_id");

                            b1.Property<string>("Postcode")
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_postcode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_street");

                            b1.HasKey("OrderId");

                            b1.ToTable("order", "order");

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_order_order_id");
                        });

                    b.Navigation("Account")
                        .IsRequired();

                    b.Navigation("Code")
                        .IsRequired();

                    b.Navigation("ShippingAddress")
                        .IsRequired();

                    b.Navigation("ShippingFee")
                        .IsRequired();

                    b.Navigation("Total")
                        .IsRequired();

                    b.Navigation("TotalWithDiscount")
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Order.Domain.OrderAggregate.Order", b =>
                {
                    b.Navigation("AppliedCoupons");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
