<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Haskap.EShopping.Domain\Haskap.EShopping.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Haskap.DddBase.Domain">
      <HintPath>..\..\References\Haskap.DddBase.Domain.dll</HintPath>
    </Reference>
    <Reference Include="Haskap.DddBase.Infra">
      <HintPath>..\..\References\Haskap.DddBase.Infra.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
