// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Catalog.Infra.Db.Contexts.CatalogDbContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Modules.Catalog.Infra.Db.Contexts.CatalogDbContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629142312_Attribute_Type_Pair_Added")]
    partial class Attribute_Type_Pair_Added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.AuditLog.Domain.AuditHistoryLogAggregate.AuditHistoryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ModificationDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modification_date_utc");

                    b.Property<string>("ModificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modification_type");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_user_id");

                    b.Property<string>("ObjectFullType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_full_type");

                    b.Property<string>("ObjectIds")
                        .HasColumnType("text")
                        .HasColumnName("object_ids");

                    b.Property<string>("ObjectNewValues")
                        .HasColumnType("text")
                        .HasColumnName("object_new_values");

                    b.Property<string>("ObjectOriginalValues")
                        .HasColumnType("text")
                        .HasColumnName("object_original_values");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ownership_type");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_history_log");

                    b.ToTable("audit_history_log", "audit_log", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Catalog.Domain.CategoryAggregate.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_category_name");

                    b.ToTable("category", "catalog");
                });

            modelBuilder.Entity("Modules.Catalog.Domain.CategoryAggregate.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_category");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_product_category_category_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_category_product_id");

                    b.ToTable("product_category", "catalog");
                });

            modelBuilder.Entity("Modules.Catalog.Domain.ColorAttributeAggregate.ColorAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_color_attribute");

                    b.ToTable("color_attribute", "catalog");
                });

            modelBuilder.Entity("Modules.Catalog.Domain.ProductAggregate.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<Guid?>("CreatedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<NpgsqlTsVector>("SearchVectorTurkish")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector_turkish")
                        .HasComputedColumnSql("to_tsvector('turkish', \"name\" || ' ' || \"description\" || ' ' || \"sku_value\")", true);

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_product_name");

                    b.HasIndex("SearchVectorTurkish")
                        .HasDatabaseName("ix_product_search_vector_turkish");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVectorTurkish"), "GIN");

                    b.ToTable("product", "catalog");
                });

            modelBuilder.Entity("Modules.Catalog.Domain.ProductAggregate.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<Guid?>("CreatedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on_utc");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_user_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<NpgsqlTsVector>("SearchVectorTurkish")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector_turkish")
                        .HasComputedColumnSql("to_tsvector('turkish', \"sku_value\")", true);

                    b.HasKey("Id")
                        .HasName("pk_product_variant");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_variant_product_id");

                    b.HasIndex("SearchVectorTurkish")
                        .HasDatabaseName("ix_product_variant_search_vector_turkish");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVectorTurkish"), "GIN");

                    b.ToTable("product_variant", "catalog");
                });

            modelBuilder.Entity("Modules.Catalog.Domain.SizeAttributeAggregate.SizeAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_size_attribute");

                    b.ToTable("size_attribute", "catalog");
                });

            modelBuilder.Entity("Modules.Catalog.Domain.CategoryAggregate.Category", b =>
                {
                    b.OwnsOne("Haskap.EShopping.Domain.Common.Slug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("slug_value");

                            b1.HasKey("CategoryId");

                            b1.ToTable("category", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId")
                                .HasConstraintName("fk_category_category_id");
                        });

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Catalog.Domain.CategoryAggregate.ProductCategory", b =>
                {
                    b.HasOne("Modules.Catalog.Domain.CategoryAggregate.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_category_category_category_id");

                    b.HasOne("Modules.Catalog.Domain.ProductAggregate.Product", null)
                        .WithMany("Categories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_category_product_product_id");
                });

            modelBuilder.Entity("Modules.Catalog.Domain.ProductAggregate.Product", b =>
                {
                    b.OwnsOne("Modules.Catalog.Domain.ProductAggregate.Sku", "Sku", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("sku_value");

                            b1.HasKey("ProductId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_product_sku_value");

                            b1.ToTable("product", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_product_product_id");
                        });

                    b.OwnsMany("Modules.Catalog.Domain.ProductAggregate.ProductAttributeTypeForDetails", "AttributeTypePairForDetails", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AttributeType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("attribute_type");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_id");

                            b1.HasKey("Id")
                                .HasName("pk_product_attribute_type_for_details");

                            b1.HasIndex("ProductId")
                                .HasDatabaseName("ix_product_attribute_type_for_details_product_id");

                            b1.ToTable("product_attribute_type_for_details", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_product_attribute_type_for_details_product_product_id");
                        });

                    b.Navigation("AttributeTypePairForDetails");

                    b.Navigation("Sku")
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Catalog.Domain.ProductAggregate.ProductVariant", b =>
                {
                    b.HasOne("Modules.Catalog.Domain.ProductAggregate.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_variant_product_product_id");

                    b.OwnsMany("Modules.Catalog.Domain.ProductAggregate.ProductAttribute", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("AttributeType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("attribute_type");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("description");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("display_name");

                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_variant_id");

                            b1.Property<NpgsqlTsVector>("SearchVectorTurkish")
                                .IsRequired()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("tsvector")
                                .HasColumnName("search_vector_turkish")
                                .HasComputedColumnSql("to_tsvector('turkish', display_name || ' ' || value || ' ' || COALESCE(description, ''))", true);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("value");

                            b1.HasKey("Id")
                                .HasName("pk_product_attribute");

                            b1.HasIndex("ProductVariantId")
                                .HasDatabaseName("ix_product_attribute_product_variant_id");

                            b1.HasIndex("SearchVectorTurkish")
                                .HasDatabaseName("ix_product_attribute_search_vector_turkish");

                            NpgsqlIndexBuilderExtensions.HasMethod(b1.HasIndex("SearchVectorTurkish"), "GIN");

                            b1.ToTable("product_attribute", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId")
                                .HasConstraintName("fk_product_attribute_product_variant_product_variant_id");
                        });

                    b.OwnsMany("Modules.Catalog.Domain.ProductAggregate.ProductPicture", "Pictures", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean")
                                .HasColumnName("is_primary");

                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_variant_id");

                            b1.HasKey("Id")
                                .HasName("pk_product_picture");

                            b1.HasIndex("ProductVariantId")
                                .HasDatabaseName("ix_product_picture_product_variant_id");

                            b1.ToTable("product_picture", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId")
                                .HasConstraintName("fk_product_picture_product_variant_product_variant_id");

                            b1.OwnsOne("Haskap.DddBase.Domain.Common.File", "PhotoFile", b2 =>
                                {
                                    b2.Property<Guid>("ProductPictureId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Extension")
                                        .HasColumnType("text")
                                        .HasColumnName("photo_file_extension");

                                    b2.Property<string>("NewName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("photo_file_new_name");

                                    b2.Property<string>("OriginalName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("photo_file_original_name");

                                    b2.HasKey("ProductPictureId");

                                    b2.ToTable("product_picture", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductPictureId")
                                        .HasConstraintName("fk_product_picture_product_picture_id");
                                });

                            b1.Navigation("PhotoFile")
                                .IsRequired();
                        });

                    b.OwnsOne("Haskap.EShopping.Domain.Common.Money", "OldPrice", b1 =>
                        {
                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("old_price_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("old_price_value");

                            b1.HasKey("ProductVariantId");

                            b1.ToTable("product_variant", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId")
                                .HasConstraintName("fk_product_variant_product_variant_id");
                        });

                    b.OwnsOne("Haskap.EShopping.Domain.Common.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("price_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("price_value");

                            b1.HasKey("ProductVariantId");

                            b1.ToTable("product_variant", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId")
                                .HasConstraintName("fk_product_variant_product_variant_id");
                        });

                    b.OwnsOne("Modules.Catalog.Domain.ProductAggregate.Sku", "Sku", b1 =>
                        {
                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("sku_value");

                            b1.HasKey("ProductVariantId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_product_variant_sku_value");

                            b1.ToTable("product_variant", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId")
                                .HasConstraintName("fk_product_variant_product_variant_id");
                        });

                    b.OwnsOne("Haskap.EShopping.Domain.Common.Slug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("slug_value");

                            b1.HasKey("ProductVariantId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_product_variant_slug_value");

                            b1.ToTable("product_variant", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId")
                                .HasConstraintName("fk_product_variant_product_variant_id");
                        });

                    b.OwnsOne("Modules.Catalog.Domain.ProductAggregate.StockQuantity", "StockQuantity", b1 =>
                        {
                            b1.Property<Guid>("ProductVariantId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("stock_quantity_value");

                            b1.HasKey("ProductVariantId");

                            b1.ToTable("product_variant", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductVariantId")
                                .HasConstraintName("fk_product_variant_product_variant_id");
                        });

                    b.Navigation("Attributes");

                    b.Navigation("OldPrice")
                        .IsRequired();

                    b.Navigation("Pictures");

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Sku")
                        .IsRequired();

                    b.Navigation("Slug")
                        .IsRequired();

                    b.Navigation("StockQuantity")
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Catalog.Domain.ProductAggregate.Product", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
