<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Modules.Discount.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Modules.Discount.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Application\Haskap.EShopping.Application.Dtos\Haskap.EShopping.Application.Dtos.csproj" />
  </ItemGroup>

</Project>
