<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Modules.Order.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Modules.Order.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application.Dtos\Application.Dtos.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Haskap.DddBase.Application.Contracts">
      <HintPath>..\..\..\References\Haskap.DddBase.Application.Contracts.dll</HintPath>
    </Reference>
    <Reference Include="Haskap.DddBase.Utilities">
      <HintPath>..\..\..\References\Haskap.DddBase.Utilities.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
