// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Discount.Infra.Db.Contexts.DiscountDbContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Discount.Infra.Db.Contexts.DiscountDbContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724152912_Couponlar_Birlestirildi")]
    partial class Couponlar_Birlestirildi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("discount")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.AuditLog.Domain.AuditHistoryLogAggregate.AuditHistoryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ModificationDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modification_date_utc");

                    b.Property<string>("ModificationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modification_type");

                    b.Property<Guid?>("ModifiedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("modified_user_id");

                    b.Property<string>("ObjectFullType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_full_type");

                    b.Property<string>("ObjectIds")
                        .HasColumnType("text")
                        .HasColumnName("object_ids");

                    b.Property<string>("ObjectNewValues")
                        .HasColumnType("text")
                        .HasColumnName("object_new_values");

                    b.Property<string>("ObjectOriginalValues")
                        .HasColumnType("text")
                        .HasColumnName("object_original_values");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ownership_type");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_history_log");

                    b.ToTable("audit_history_log", "audit_log", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Discount.Domain.CouponAggregate.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("pk_coupon");

                    b.ToTable("coupon", "discount");
                });

            modelBuilder.Entity("Modules.Discount.Domain.CouponAggregate.CouponCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid")
                        .HasColumnName("coupon_id");

                    b.HasKey("Id")
                        .HasName("pk_coupon_category");

                    b.HasIndex("CouponId")
                        .HasDatabaseName("ix_coupon_category_coupon_id");

                    b.ToTable("coupon_category", "discount");
                });

            modelBuilder.Entity("Modules.Discount.Domain.CouponAggregate.CouponSelectedProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CouponId")
                        .HasColumnType("uuid")
                        .HasColumnName("coupon_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.HasKey("Id")
                        .HasName("pk_coupon_selected_product_variant");

                    b.HasIndex("CouponId")
                        .HasDatabaseName("ix_coupon_selected_product_variant_coupon_id");

                    b.ToTable("coupon_selected_product_variant", "discount");
                });

            modelBuilder.Entity("Modules.Discount.Domain.CouponAggregate.Coupon", b =>
                {
                    b.OwnsOne("Haskap.EShopping.Domain.Common.Money", "BasketMinTotalAmount", b1 =>
                        {
                            b1.Property<Guid>("CouponId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("basket_min_total_amount_currency");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("basket_min_total_amount_value");

                            b1.HasKey("CouponId");

                            b1.ToTable("coupon", "discount");

                            b1.WithOwner()
                                .HasForeignKey("CouponId")
                                .HasConstraintName("fk_coupon_coupon_id");
                        });

                    b.OwnsOne("Modules.Discount.Domain.CouponAggregate.DateRange", "DateRange", b1 =>
                        {
                            b1.Property<Guid>("CouponId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("UtcEndDateTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("date_range_utc_end_date_time");

                            b1.Property<DateTime>("UtcStartDateTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("date_range_utc_start_date_time");

                            b1.HasKey("CouponId");

                            b1.ToTable("coupon", "discount");

                            b1.WithOwner()
                                .HasForeignKey("CouponId")
                                .HasConstraintName("fk_coupon_coupon_id");
                        });

                    b.OwnsOne("Modules.Discount.Domain.CouponAggregate.Discount", "Discount", b1 =>
                        {
                            b1.Property<Guid>("CouponId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal?>("FixedDiscountAmountValue")
                                .HasColumnType("numeric")
                                .HasColumnName("discount_fixed_discount_amount_value");

                            b1.Property<decimal?>("FixedPriceValue")
                                .HasColumnType("numeric")
                                .HasColumnName("discount_fixed_price_value");

                            b1.Property<bool>("IsFreeShippingDiscount")
                                .HasColumnType("boolean")
                                .HasColumnName("discount_is_free_shipping_discount");

                            b1.Property<decimal?>("PercentageDiscountValue")
                                .HasColumnType("numeric")
                                .HasColumnName("discount_percentage_discount_value");

                            b1.Property<int?>("QuantityDivider")
                                .HasColumnType("integer")
                                .HasColumnName("discount_quantity_divider");

                            b1.HasKey("CouponId");

                            b1.ToTable("coupon", "discount");

                            b1.WithOwner()
                                .HasForeignKey("CouponId")
                                .HasConstraintName("fk_coupon_coupon_id");
                        });

                    b.OwnsOne("Modules.Discount.Domain.CouponAggregate.UsageCount", "UsageCount", b1 =>
                        {
                            b1.Property<Guid>("CouponId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Limit")
                                .HasColumnType("integer")
                                .HasColumnName("usage_count_limit");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("usage_count_value");

                            b1.HasKey("CouponId");

                            b1.ToTable("coupon", "discount");

                            b1.WithOwner()
                                .HasForeignKey("CouponId")
                                .HasConstraintName("fk_coupon_coupon_id");
                        });

                    b.Navigation("BasketMinTotalAmount")
                        .IsRequired();

                    b.Navigation("DateRange")
                        .IsRequired();

                    b.Navigation("Discount")
                        .IsRequired();

                    b.Navigation("UsageCount")
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Discount.Domain.CouponAggregate.CouponCategory", b =>
                {
                    b.HasOne("Modules.Discount.Domain.CouponAggregate.Coupon", null)
                        .WithMany("Categories")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coupon_category_coupon_coupon_id");
                });

            modelBuilder.Entity("Modules.Discount.Domain.CouponAggregate.CouponSelectedProductVariant", b =>
                {
                    b.HasOne("Modules.Discount.Domain.CouponAggregate.Coupon", null)
                        .WithMany("SelectedProductVariants")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coupon_selected_product_variant_coupon_coupon_id");
                });

            modelBuilder.Entity("Modules.Discount.Domain.CouponAggregate.Coupon", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("SelectedProductVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
