<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Modules.Account.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Modules.Account.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application.Dtos\Application.Dtos.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Haskap.DddBase.Domain">
      <HintPath>..\..\..\References\Haskap.DddBase.Domain.dll</HintPath>
    </Reference>
    <Reference Include="Haskap.DddBase.Domain.Shared">
      <HintPath>..\..\..\References\Haskap.DddBase.Domain.Shared.dll</HintPath>
    </Reference>
    <Reference Include="Haskap.DddBase.Infra">
      <HintPath>..\..\..\References\Haskap.DddBase.Infra.dll</HintPath>
    </Reference>
    <Reference Include="Haskap.DddBase.Infra.Db.Contexts.EfCoreContext">
      <HintPath>..\..\..\References\Haskap.DddBase.Infra.Db.Contexts.EfCoreContext.dll</HintPath>
    </Reference>
    <Reference Include="Haskap.DddBase.Infra.Db.Contexts.NpgsqlDbContext">
      <HintPath>..\..\..\References\Haskap.DddBase.Infra.Db.Contexts.NpgsqlDbContext.dll</HintPath>
    </Reference>
    <Reference Include="Haskap.DddBase.Utilities">
      <HintPath>..\..\..\References\Haskap.DddBase.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="Modules.AuditLog.Domain">
      <HintPath>..\..\..\References\Modules.AuditLog.Domain.dll</HintPath>
    </Reference>
    <Reference Include="Modules.AuditLog.Infra">
      <HintPath>..\..\..\References\Modules.AuditLog.Infra.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Db\Contexts\AccountDbContext\Migrations\" />
  </ItemGroup>

</Project>
